package opengpu.testutil

import chisel3.RawModule
import chisel3.simulator.{PeekPokeAPI, Simulator}
import svsim.CommonCompilationSettings
import svsim.verilator.Backend

import java.nio.file.{Files, Path, Paths}
import java.util.concurrent.atomic.AtomicInteger
import scala.jdk.CollectionConverters._

/** Cached drop-in replacement for `chisel3.simulator.EphemeralSimulator.simulate`.
  *
  * Every `EphemeralSimulator.simulate` call elaborates the design with firtool and
  * then hands the RTL to Verilator in a private temporary directory, so the C++
  * model is rebuilt from scratch.  Compilation, not simulation, is what this test
  * suite spends its time on: the module suites call `simulate` several hundred
  * times, and even a trivial two-lane ALU costs a few seconds per call.
  *
  * This harness leaves the Chisel elaboration path alone and only interposes on
  * the Verilator executable.  `GpuSim` points the simulator at a generated shim
  * that keys the compiled model by a digest of the Verilog sources and the
  * compiler flags, so simulating an unchanged design again hard-links the cached
  * executable instead of rebuilding it.  Peeking, poking, stepping and the
  * assertion checks keep running through the stock `chisel3.simulator.Simulator`
  * implementation, and a stale cache is impossible because changed RTL produces
  * a different digest.
  *
  * The cache lives under `target/chiselsim`, so `sbt clean` drops it.  Pass
  * `-Dopengpu.simCache=off` to run against the real Verilator without caching,
  * and set `GPU_SIM_DEBUG=1` to log every build the shim restores or publishes.
  */
object GpuSim extends PeekPokeAPI {

  private val cacheSetting = sys.props.get("opengpu.simCache")
  private val enabled = !cacheSetting.contains("off")
  private val root = Paths.get(cacheSetting.filter(_ => enabled).getOrElse("target/chiselsim"))
  private val binDirectory = root.resolve("bin")
  private val cacheDirectory = root.resolve("cache")

  private val slots = new AtomicInteger(0)

  private val backend: Backend = if (enabled) locateVerilator() match {
    case Some(verilator) =>
      val shim = binDirectory.resolve("verilator")
      Files.createDirectories(binDirectory)
      Files.write(shim, shimScript(verilator, cacheDirectory.toAbsolutePath).getBytes("UTF-8"))
      shim.toFile.setExecutable(true)
      new Backend(shim.toAbsolutePath.toString)
    case None =>
      Backend.initializeFromProcessEnvironment()
  } else {
    Backend.initializeFromProcessEnvironment()
  }

  private final class Runner(val workspacePath: String) extends Simulator[Backend] {
    val backend: Backend = GpuSim.backend
    val tag: String = "verilator"
    val commonCompilationSettings: CommonCompilationSettings = CommonCompilationSettings.default
    val backendSpecificCompilationSettings: Backend.CompilationSettings = new Backend.CompilationSettings()
  }

  /** Simulate `module`, handing `body` the elaborated module exactly like
    * `chisel3.simulator.EphemeralSimulator.simulate`.
    */
  def simulate[T <: RawModule](module: => T)(body: T => Unit): Unit = {
    Files.createDirectories(root)
    val workspace = root.resolve(s"slot-${slots.getAndIncrement()}")
    try {
      new Runner(workspace.toString)
        .simulate(module)(simulated => body(simulated.wrapped))
        .result
    } finally {
      delete(workspace)
    }
  }

  private def locateVerilator(): Option[String] = {
    val absoluteBin = binDirectory.toAbsolutePath
    sys.env
      .getOrElse("PATH", "")
      .split(java.io.File.pathSeparatorChar)
      .iterator
      .map(dir => Paths.get(dir).resolve("verilator"))
      .filter(p => Files.isExecutable(p) && !p.toAbsolutePath.startsWith(absoluteBin))
      .map(_.toAbsolutePath.toString)
      .toSeq
      .headOption
  }

  /** A Verilator front end that serves a content-addressed cache of built models.
    *
    * svsim runs Verilator in `<workspace>/workdir-verilator` and expects the
    * executable named by `-o` to appear next to it.  The shim digests the files
    * in the `-F` filelist together with the compiler flags, with the workspace
    * prefix stripped so the digest does not depend on where the run happened, and
    * then either restores a previously built executable or runs Verilator and
    * publishes the result.  Anything unexpected falls back to plain Verilator.
    */
  private def shimScript(verilator: String, cache: Path): String =
    s"""#!/bin/sh
       |# Generated by opengpu.testutil.GpuSim.
       |verilator='$verilator'
       |cache='$cache'
       |log="$cache/shim.log"
       |out=''
       |mdir=''
       |filelist=''
       |prev=''
       |for arg in "$$@"; do
       |  case "$$prev" in
       |    -o) out=$$arg ;;
       |    --Mdir) mdir=$$arg ;;
       |    -F) filelist=$$arg ;;
       |  esac
       |  case "$$arg" in
       |    -o|--Mdir|-F) prev=$$arg ;;
       |    *) prev='' ;;
       |  esac
       |done
       |[ -n "$$mdir" ] || mdir='verilated-sources'
       |[ -n "$$out" ] || out='../simulation'
       |mkdir -p "$$mdir" 2>/dev/null
       |workspace=$$(cd .. 2>/dev/null && pwd)
       |physical=$$(cd .. 2>/dev/null && pwd -P)
       |dest=$$(cd "$$mdir/$$(dirname "$$out")" 2>/dev/null && pwd)/$$(basename "$$out")
       |key=$$(
       |  {
       |    "$$verilator" --version 2>/dev/null
       |    printf '%s\\n' "$$@" | sed "s|$$workspace/|WS/|g; s|$$physical/|WS/|g"
       |    if [ -n "$$filelist" ] && [ -f "$$filelist" ]; then
       |      while IFS= read -r f; do
       |        f=$$(printf '%s' "$$f" | sed "s|$$workspace/||g; s|$$physical/||g")
       |        [ -f "$$f" ] || continue
       |        printf '%s %s\\n' "$$f" "$$(cksum < "$$f" | cut -d' ' -f1,2)"
       |      done < "$$filelist"
       |    fi
       |  } 2>/dev/null | cksum | cut -d' ' -f1,2 | tr -d ' \\n'
       |)
       |hit="$$cache/$$key"
       |mkdir -p "$$cache" 2>/dev/null
       |if [ -n "$$key" ] && [ -x "$$hit" ]; then
       |  if mkdir -p "$$(dirname "$$dest")" 2>/dev/null &&
       |     { ln -f "$$hit" "$$dest" 2>/dev/null || cp "$$hit" "$$dest" 2>/dev/null; } &&
       |     chmod +x "$$dest" 2>/dev/null && [ -x "$$dest" ]; then
       |    if [ -n "$${GPU_SIM_DEBUG:-}" ]; then printf 'hit %s\\n' "$$key" >> "$$log"; fi
       |    exit 0
       |  fi
       |fi
       |"$$verilator" "$$@"
       |status=$$?
       |if [ "$$status" = 0 ] && [ -n "$$key" ] && [ -x "$$dest" ]; then
       |  tmp="$$hit.tmp.$$$$"
       |  if cp "$$dest" "$$tmp" 2>/dev/null && chmod +x "$$tmp" 2>/dev/null &&
       |     mv -f "$$tmp" "$$hit" 2>/dev/null; then
       |    if [ -n "$${GPU_SIM_DEBUG:-}" ]; then printf 'store %s\\n' "$$key" >> "$$log"; fi
       |  else
       |    rm -f "$$tmp"
       |  fi
       |else
       |  if [ -n "$${GPU_SIM_DEBUG:-}" ]; then
       |    printf 'miss status=%s key=%s dest=%s\\n' "$$status" "$$key" "$$dest" >> "$$log"
       |  fi
       |fi
       |exit "$$status"
       |""".stripMargin

  private def delete(path: Path): Unit = {
    if (Files.exists(path)) {
      val stream = Files.walk(path)
      try {
        stream
          .sorted(java.util.Comparator.reverseOrder[Path]())
          .iterator()
          .asScala
          .foreach(p => Files.deleteIfExists(p))
      } finally stream.close()
    }
  }
}
