package gpu.core.frontend.decode

import chisel3._
import chisel3.util._
import chisel3.util.experimental.decode.{
  BoolDecodeField,
  DecodeField,
  DecodePattern,
  DecodeTable
}
import gpu.core.execute.integer.AluOp

object BranchOp {
  val width = 3
  val none = 0.U(width.W)
  val eq   = 1.U(width.W)
  val ne   = 2.U(width.W)
  val lt   = 3.U(width.W)
  val ge   = 4.U(width.W)
  val ltu  = 5.U(width.W)
  val geu  = 6.U(width.W)
}

private object ImmSel {
  val width = 3
  val none = 0
  val i = 1
  val s = 2
  val b = 3
  val u = 4
  val j = 5
  val z = 6
}

class DecodeSignals extends Bundle {
  val legal = Bool()
  val rs1 = UInt(5.W)
  val rs2 = UInt(5.W)
  val rd = UInt(5.W)
  val immediate = UInt(32.W)

  val aluOp = UInt(AluOp.width.W)
  val branchOp = UInt(BranchOp.width.W)
  val useImmediate = Bool()
  val usePc = Bool()
  val useRs1 = Bool()
  val useRs2 = Bool()
  val writeRd = Bool()
  val memoryRead = Bool()
  val memoryWrite = Bool()
  val jump = Bool()
  val multiply = Bool()
  val divide = Bool()
  val atomic = Bool()
  val atomicOp = UInt(4.W)
  val csr = Bool()
  val system = Bool()
  val fence = Bool()
  val barrier = Bool()
  val vectorBranch = Bool()
  val join = Bool()
  val cease = Bool()
}

/** One row in the RV32I decode database.
  *
  * This follows opengpu's CoreDecoder structure: instruction metadata is kept
  * in DecodePattern objects and each control signal is generated by a
  * DecodeField. Adding an instruction therefore means adding a table row, not
  * another branch to the decoder circuit.
  */
private case class Rv32Pattern(
  name: String,
  encoding: String,
  alu: Int = 0,
  branch: Int = 0,
  imm: Int = 0,
  useImmediate: Boolean = false,
  usePc: Boolean = false,
  useRs1: Boolean = false,
  useRs2: Boolean = false,
  writeRd: Boolean = false,
  memoryRead: Boolean = false,
  memoryWrite: Boolean = false,
  jump: Boolean = false,
  multiply: Boolean = false,
  divide: Boolean = false,
  atomic: Boolean = false,
  atomicOp: Int = 0,
  csr: Boolean = false,
  system: Boolean = false,
  fence: Boolean = false,
  barrier: Boolean = false,
  vectorBranch: Boolean = false,
  join: Boolean = false,
  cease: Boolean = false
) extends DecodePattern {
  override def bitPat: BitPat = BitPat("b" + encoding)
}

private abstract class UIntField(
  override val name: String,
  width: Int,
  defaultValue: Int = 0
) extends DecodeField[Rv32Pattern, UInt] {
  override def chiselType: UInt = UInt(width.W)
  override def default: BitPat = BitPat(defaultValue.U(width.W))
  protected def value(pattern: Rv32Pattern): Int
  override def genTable(pattern: Rv32Pattern): BitPat = BitPat(value(pattern).U(width.W))
}

private abstract class BoolField(override val name: String)
    extends BoolDecodeField[Rv32Pattern] {
  override def default: BitPat = n
  protected def value(pattern: Rv32Pattern): Boolean
  override def genTable(pattern: Rv32Pattern): BitPat = if (value(pattern)) y else n
}

private object Rv32Decode {
  object Legal extends BoolField("legal") {
    override protected def value(pattern: Rv32Pattern): Boolean = true
  }
  object Alu extends UIntField("alu", AluOp.width) {
    override protected def value(pattern: Rv32Pattern): Int = pattern.alu
  }
  object Branch extends UIntField("branch", BranchOp.width) {
    override protected def value(pattern: Rv32Pattern): Int = pattern.branch
  }
  object Immediate extends UIntField("immediate", ImmSel.width) {
    override protected def value(pattern: Rv32Pattern): Int = pattern.imm
  }
  object UseImmediate extends BoolField("useImmediate") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.useImmediate
  }
  object UsePc extends BoolField("usePc") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.usePc
  }
  object UseRs1 extends BoolField("useRs1") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.useRs1
  }
  object UseRs2 extends BoolField("useRs2") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.useRs2
  }
  object WriteRd extends BoolField("writeRd") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.writeRd
  }
  object MemoryRead extends BoolField("memoryRead") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.memoryRead
  }
  object MemoryWrite extends BoolField("memoryWrite") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.memoryWrite
  }
  object Jump extends BoolField("jump") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.jump
  }
  object Multiply extends BoolField("multiply") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.multiply
  }
  object Divide extends BoolField("divide") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.divide
  }
  object Atomic extends BoolField("atomic") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.atomic
  }
  object AtomicOp extends UIntField("atomicOp", 4) {
    override protected def value(pattern: Rv32Pattern): Int = pattern.atomicOp
  }
  object Csr extends BoolField("csr") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.csr
  }
  object System extends BoolField("system") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.system
  }
  object Fence extends BoolField("fence") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.fence
  }
  object Barrier extends BoolField("barrier") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.barrier
  }
  object VectorBranch extends BoolField("vectorBranch") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.vectorBranch
  }
  object Join extends BoolField("join") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.join
  }
  object Cease extends BoolField("cease") {
    override protected def value(pattern: Rv32Pattern): Boolean = pattern.cease
  }

  private def op(name: String, funct3: String, alu: Int): Rv32Pattern =
    Rv32Pattern(name, s"0000000??????????$funct3?????0110011",
      alu = alu, useRs1 = true, useRs2 = true, writeRd = true)

  private def opAlt(name: String, funct3: String, alu: Int): Rv32Pattern =
    Rv32Pattern(name, s"0100000??????????$funct3?????0110011",
      alu = alu, useRs1 = true, useRs2 = true, writeRd = true)

  private def opImm(name: String, funct3: String, alu: Int): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????0010011",
      alu = alu,
      imm = ImmSel.i,
      useImmediate = true,
      useRs1 = true,
      writeRd = true
    )

  private def load(name: String, funct3: String): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????0000011",
      imm = ImmSel.i,
      useImmediate = true,
      useRs1 = true,
      writeRd = true,
      memoryRead = true
    )

  private def store(name: String, funct3: String): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????0100011",
      imm = ImmSel.s,
      useImmediate = true,
      useRs1 = true,
      useRs2 = true,
      memoryWrite = true
    )

  private def branch(name: String, funct3: String, branchOp: Int): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????1100011",
      branch = branchOp,
      imm = ImmSel.b,
      useRs1 = true,
      useRs2 = true
    )

  private def mulDiv(name: String, funct3: String, isDivide: Boolean): Rv32Pattern =
    Rv32Pattern(
      name,
      s"0000001??????????$funct3?????0110011",
      useRs1 = true,
      useRs2 = true,
      writeRd = true,
      multiply = !isDivide,
      divide = isDivide
    )

  private def amo(name: String, funct5: String, operation: Int): Rv32Pattern =
    Rv32Pattern(
      name,
      s"$funct5????????????010?????0101111",
      useRs1 = true,
      useRs2 = true,
      writeRd = true,
      memoryRead = true,
      atomic = true,
      atomicOp = operation
    )

  private def csr(name: String, funct3: String, immediate: Boolean): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????1110011",
      imm = if (immediate) ImmSel.z else ImmSel.none,
      useImmediate = immediate,
      useRs1 = !immediate,
      writeRd = true,
      csr = true,
      system = true
    )

  private def vectorBranch(name: String, funct3: String, branchOp: Int): Rv32Pattern =
    Rv32Pattern(
      name,
      s"?????????????????$funct3?????1011011",
      branch = branchOp,
      imm = ImmSel.b,
      useRs1 = true,
      useRs2 = true,
      vectorBranch = true
    )

  val patterns: Seq[Rv32Pattern] = Seq(
    op("add",  "000", 0),
    opAlt("sub", "000", 1),
    op("sll",  "001", 2),
    op("slt",  "010", 3),
    op("sltu", "011", 4),
    op("xor",  "100", 5),
    op("srl",  "101", 6),
    opAlt("sra", "101", 7),
    op("or",   "110", 8),
    op("and",  "111", 9),

    opImm("addi",  "000", 0),
    Rv32Pattern("slli", "0000000??????????001?????0010011",
      alu = 2, imm = ImmSel.i, useImmediate = true, useRs1 = true, writeRd = true),
    opImm("slti",  "010", 3),
    opImm("sltiu", "011", 4),
    opImm("xori",  "100", 5),
    Rv32Pattern("srli", "0000000??????????101?????0010011",
      alu = 6, imm = ImmSel.i, useImmediate = true, useRs1 = true, writeRd = true),
    Rv32Pattern("srai", "0100000??????????101?????0010011",
      alu = 7, imm = ImmSel.i, useImmediate = true, useRs1 = true, writeRd = true),
    opImm("ori",   "110", 8),
    opImm("andi",  "111", 9),

    load("lb",  "000"),
    load("lh",  "001"),
    load("lw",  "010"),
    load("lbu", "100"),
    load("lhu", "101"),
    store("sb", "000"),
    store("sh", "001"),
    store("sw", "010"),

    branch("beq",  "000", 1),
    branch("bne",  "001", 2),
    branch("blt",  "100", 3),
    branch("bge",  "101", 4),
    branch("bltu", "110", 5),
    branch("bgeu", "111", 6),

    Rv32Pattern("lui", "?????????????????????????0110111",
      alu = 10, imm = ImmSel.u, useImmediate = true, writeRd = true),
    Rv32Pattern("auipc", "?????????????????????????0010111",
      imm = ImmSel.u, useImmediate = true, usePc = true, writeRd = true),
    Rv32Pattern("jal", "?????????????????????????1101111",
      imm = ImmSel.j, writeRd = true, jump = true),
    Rv32Pattern("jalr", "?????????????????000?????1100111",
      imm = ImmSel.i, useImmediate = true, useRs1 = true,
      writeRd = true, jump = true),

    mulDiv("mul",    "000", isDivide = false),
    mulDiv("mulh",   "001", isDivide = false),
    mulDiv("mulhsu", "010", isDivide = false),
    mulDiv("mulhu",  "011", isDivide = false),
    mulDiv("div",    "100", isDivide = true),
    mulDiv("divu",   "101", isDivide = true),
    mulDiv("rem",    "110", isDivide = true),
    mulDiv("remu",   "111", isDivide = true),

    amo("amoadd.w",  "00000", 1),
    amo("amoswap.w", "00001", 0),
    amo("amoxor.w",  "00100", 2),
    amo("amoor.w",   "01000", 3),
    amo("amoand.w",  "01100", 4),
    amo("amomin.w",  "10000", 5),
    amo("amomax.w",  "10100", 6),
    amo("amominu.w", "11000", 7),
    amo("amomaxu.w", "11100", 8),

    csr("csrrw",  "001", immediate = false),
    csr("csrrs",  "010", immediate = false),
    csr("csrrc",  "011", immediate = false),
    csr("csrrwi", "101", immediate = true),
    csr("csrrsi", "110", immediate = true),
    csr("csrrci", "111", immediate = true),
    Rv32Pattern("ecall",  "00000000000000000000000001110011", system = true),
    Rv32Pattern("ebreak", "00000000000100000000000001110011", system = true),
    Rv32Pattern("fence",  "????????????00000000000000001111",
      system = true, fence = true),
    Rv32Pattern("fence.i", "00000000000000000001000000001111",
      system = true, fence = true),
    // GPU workgroup barrier, encoded in the RISC-V custom-0 opcode space.
    Rv32Pattern("gpu.barrier", "00000000000000000000000000001011",
      system = true, barrier = true),

    vectorBranch("vbeq",  "000", BranchOp.eq.litValue.toInt),
    vectorBranch("vbne",  "001", BranchOp.ne.litValue.toInt),
    Rv32Pattern("join", "?????????????????010?????1011011",
      system = true, join = true),
    vectorBranch("vblt",  "100", BranchOp.lt.litValue.toInt),
    vectorBranch("vbge",  "101", BranchOp.ge.litValue.toInt),
    vectorBranch("vbltu", "110", BranchOp.ltu.litValue.toInt),
    vectorBranch("vbgeu", "111", BranchOp.geu.litValue.toInt),
    Rv32Pattern("cease", "00110000010100000000000001110011",
      system = true, cease = true)
  )

  val fields: Seq[DecodeField[Rv32Pattern, _ <: Data]] = Seq(
    Legal,
    Alu,
    Branch,
    Immediate,
    UseImmediate,
    UsePc,
    UseRs1,
    UseRs2,
    WriteRd,
    MemoryRead,
    MemoryWrite,
    Jump,
    Multiply,
    Divide,
    Atomic,
    AtomicOp,
    Csr,
    System,
    Fence,
    Barrier,
    VectorBranch,
    Join,
    Cease
  )

  val table = new DecodeTable(patterns, fields)
}

/** Table-driven combinational decoder for the RV32I subset used by GPU lanes. */
class RiscVDecoder extends Module {
  val io = IO(new Bundle {
    val instruction = Input(UInt(32.W))
    val decoded = Output(new DecodeSignals)
  })

  val instruction = io.instruction
  val decoded = Rv32Decode.table.decode(instruction)
  val immediateSelection = decoded(Rv32Decode.Immediate)

  val immI = Cat(Fill(20, instruction(31)), instruction(31, 20))
  val immS = Cat(Fill(20, instruction(31)), instruction(31, 25), instruction(11, 7))
  val immB = Cat(Fill(19, instruction(31)), instruction(31), instruction(7),
    instruction(30, 25), instruction(11, 8), 0.U(1.W))
  val immU = Cat(instruction(31, 12), 0.U(12.W))
  val immJ = Cat(Fill(11, instruction(31)), instruction(31), instruction(19, 12),
    instruction(20), instruction(30, 21), 0.U(1.W))
  val immZ = Cat(0.U(27.W), instruction(19, 15))

  io.decoded.legal := decoded(Rv32Decode.Legal)
  io.decoded.rs1 := instruction(19, 15)
  io.decoded.rs2 := instruction(24, 20)
  io.decoded.rd := instruction(11, 7)
  io.decoded.immediate := MuxLookup(immediateSelection, 0.U)(Seq(
    ImmSel.i.U -> immI,
    ImmSel.s.U -> immS,
    ImmSel.b.U -> immB,
    ImmSel.u.U -> immU,
    ImmSel.j.U -> immJ,
    ImmSel.z.U -> immZ
  ))
  io.decoded.aluOp := decoded(Rv32Decode.Alu)
  io.decoded.branchOp := decoded(Rv32Decode.Branch)
  io.decoded.useImmediate := decoded(Rv32Decode.UseImmediate)
  io.decoded.usePc := decoded(Rv32Decode.UsePc)
  io.decoded.useRs1 := decoded(Rv32Decode.UseRs1)
  io.decoded.useRs2 := decoded(Rv32Decode.UseRs2)
  io.decoded.writeRd := decoded(Rv32Decode.WriteRd)
  io.decoded.memoryRead := decoded(Rv32Decode.MemoryRead)
  io.decoded.memoryWrite := decoded(Rv32Decode.MemoryWrite)
  io.decoded.jump := decoded(Rv32Decode.Jump)
  io.decoded.multiply := decoded(Rv32Decode.Multiply)
  io.decoded.divide := decoded(Rv32Decode.Divide)
  io.decoded.atomic := decoded(Rv32Decode.Atomic)
  io.decoded.atomicOp := decoded(Rv32Decode.AtomicOp)
  io.decoded.csr := decoded(Rv32Decode.Csr)
  io.decoded.system := decoded(Rv32Decode.System)
  io.decoded.fence := decoded(Rv32Decode.Fence)
  io.decoded.barrier := decoded(Rv32Decode.Barrier)
  io.decoded.vectorBranch := decoded(Rv32Decode.VectorBranch)
  io.decoded.join := decoded(Rv32Decode.Join)
  io.decoded.cease := decoded(Rv32Decode.Cease)
}

/** Compatibility name retained for code using the original prototype API. */
class Decoder extends RiscVDecoder
